### ISSUE TITLE
Manage layers ids conflicts

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-web-components#171]
If 2 styles (in separate style groups) has the same layer id, a mapbox error is logged.
![image](https://user-images.githubusercontent.com/26741864/70724048-2f593a80-1cfa-11ea-8700-df2dc7b69bde.png)

We should just check if the layer Id is already added to the map before adding it

cc @mbarbet

**Comment by mbarbet** [comment]
@MohamedHamouGisaia please describe the problem

**Comment by MohamedHamouGisaia** [comment]
@mbarbet done
